### PR TITLE
Update Stroop task to more recent library version

### PR DESCRIPTION
**Pull request by FelixHenninger**
Hej Vanessa,

I've updated the example to use the most recent export workflow, which hopefully should work with the existing data storage API (so it calls `/save` directly, with form-encoded data). I'm not sure how to test this locally, guessing that the container needs to be rebuilt?

Best,

-Felix

### CODE REVIEW

**Review by vsoch — COMMENTED** [review]
Excellent! Actually as soon as we merge it will be rebuilt automatically :) That's the great thing about the setup! So I'm afk finishing my run, bit after I merge in a few minutes the container should be ready to pull and test!

**Comment by vsoch** [comment]
https://circleci.com/workflow-run/c9696607-a016-451c-a42f-eab9024bb3dd <-- here it is!!

**Comment by vsoch** [comment]
I need to add the direct link in the main README, forgot to do that 😋

**Comment by vsoch** [comment]
And once we get this set up, given some consistent set of experiments, I can create a builder robot using selenium to actually test the experiments. There was a PR this morning for the stroop and I realized I wasn't doing this, along with versioning. If others are going to use the experiments it's only proper to provide each one with a version and container (labjs too!)

**Comment by FelixHenninger** [comment]
Thanks for fixing this! I have some thoughts about testing studies, one more point we should discuss sometime!

**Comment by vsoch** [comment]
Agreed! I was able to get about half of the new docs done, here is the first part --> https://expfactory.github.io/expfactory/integration-labjs and for the labjs part I'll focus heavily on the first part of that, creation in LabJS and then export. I actually spent a bunch of time writing up today how we debugged the issue (because it's really interesting when I think about it!) I'm hoping to finish that up in the next few days, and then the docs... by the end of the week.

**Pull request merged**
